### ISSUE TITLE
AttributeError: 'torch.cuda.ByteTensor' object has no attribute 'detach_'

### ISSUE THREAD

**Issue by Lvhhhh** [mileyan/AnyNet#2]
hello,the pytorch version is 0.4.0
when i run the commend ''python main.py --maxdisp 192 --with_spn"
the error is
[2018-11-09 10:13:52 main.py:65] INFO     channels_3d: 4
[2018-11-09 10:13:52 main.py:65] INFO     datapath: /home/lvhao/data/flythings3d/
[2018-11-09 10:13:52 main.py:65] INFO     epochs: 10
[2018-11-09 10:13:52 main.py:65] INFO     growth_rate: [4, 1, 1]
[2018-11-09 10:13:52 main.py:65] INFO     init_channels: 1
[2018-11-09 10:13:52 main.py:65] INFO     layers_3d: 4
[2018-11-09 10:13:52 main.py:65] INFO     loss_weights: [0.25, 0.5, 1.0, 1.0]
[2018-11-09 10:13:52 main.py:65] INFO     lr: 0.0005
[2018-11-09 10:13:52 main.py:65] INFO     maxdisp: 192
[2018-11-09 10:13:52 main.py:65] INFO     maxdisplist: [12, 3, 3]
[2018-11-09 10:13:52 main.py:65] INFO     nblocks: 2
[2018-11-09 10:13:52 main.py:65] INFO     print_freq: 5
[2018-11-09 10:13:52 main.py:65] INFO     resume: None
[2018-11-09 10:13:52 main.py:65] INFO     save_path: results/pretrained_anynet
[2018-11-09 10:13:52 main.py:65] INFO     spn_init_channels: 8
[2018-11-09 10:13:52 main.py:65] INFO     test_bsize: 4
[2018-11-09 10:13:52 main.py:65] INFO     train_bsize: 6
[2018-11-09 10:13:52 main.py:65] INFO     with_spn: True
[2018-11-09 10:13:54 main.py:70] INFO     Number of model parameters: 43269
[2018-11-09 10:13:54 main.py:86] INFO     Not Resume
[2018-11-09 10:13:54 main.py:90] INFO     This is 0-th epoch
Traceback (most recent call last):
  File "main.py", line 192, in <module>
    main()
  File "main.py", line 92, in main
    train(TrainImgLoader, model, optimizer, log, epoch)
  File "main.py", line 120, in train
    mask.detach_()
AttributeError: 'torch.cuda.ByteTensor' object has no attribute 'detach_'
i change the 'detach_()' into 'detach()' or 'date()' the error is still existed please tell me how to solve it?tks

**Comment by mileyan** [comment]
Could please double check the pytorch version? It should be fine for pytorch == 0.4.0.
