### ISSUE TITLE
a mistake when I compile SPN

### ISSUE THREAD

**Issue by cxzhou95** [mileyan/AnyNet#3]
Hello, Mileyan

I met a mistake when I compile SPN. Could you help me solve this problem? Thank you!

`yazhou@yazhou-wate-ubuntu:/media/yazhou/data_drive2/zcx/stereo/AnyNet-master/models/spn$ bash make.sh 
Compiling gaterecurrent2dnoind layer kernels by nvcc...
Including CUDA code.
generating /tmp/tmph1wickvg/_gaterecurrent2dnoind.c
setting the current directory to '/tmp/tmph1wickvg'
running build_ext
building '_gaterecurrent2dnoind' extension
creating media
creating media/yazhou
creating media/yazhou/data_drive2
creating media/yazhou/data_drive2/zcx
creating media/yazhou/data_drive2/zcx/stereo
creating media/yazhou/data_drive2/zcx/stereo/AnyNet-master
creating media/yazhou/data_drive2/zcx/stereo/AnyNet-master/models
creating media/yazhou/data_drive2/zcx/stereo/AnyNet-master/models/spn
creating media/yazhou/data_drive2/zcx/stereo/AnyNet-master/models/spn/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -c _gaterecurrent2dnoind.c -o ./_gaterecurrent2dnoind.o
In file included from /usr/local/cuda/include/cuda_runtime.h:91:0,
                 from /usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:13,
                 from /usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4,
                 from _gaterecurrent2dnoind.c:493:
/usr/local/cuda/include/cuda_runtime_api.h:2933:97: error: unknown type name ‘cudaFuncAttribute’
 ltin__ cudaError_t CUDARTAPI cudaFuncSetAttribute(const void *func, cudaFuncAtt
                                                                     ^
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/local/lib/python3.5/dist-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/local/lib/python3.5/dist-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/local/lib/python3.5/dist-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by mileyan** [comment]
Hi, what's your cuda version? Could you please check it first?
