### ISSUE TITLE
about data set structure

### ISSUE THREAD

**Issue by shammmmmless** [mileyan/AnyNet#9]
I get a error about data set that shown as following:
Traceback (most recent call last):
  File "main.py", line 192, in <module>
    main()
  File "main.py", line 51, in main
    args.datapath)
  File "/home/****/Cworkspace/AnyNet/dataloader/listflowfile.py", line 23, in dataloader
    monkaa_path = filepath + [x for x in image if 'monkaa' in x][0]
IndexError: list index out of range

The reason maybe I provide a wrong structure of data side, could you show me what the structure and path of scene flow data set should be?

**Comment by vwvw** [comment]
Did you manage to fix your issue?

**Comment by MJITG** [comment]
Did you manage to fix your issue?
